categories:
  giyim: "https://www.trendurunlermarket.com/giyim-C4"
  elektronik: "https://www.trendurunlermarket.com/elektronik-C5"
  ev_yasam: "https://www.trendurunlermarket.com/ev-yasam-C6"
  anne_bebek: "https://www.trendurunlermarket.com/anne-bebek-C7"
  kozmetik_bakim: "https://www.trendurunlermarket.com/kozmetik-bakim-C8"
  mucevher_saat: "https://www.trendurunlermarket.com/mucevher-saat-C9"
  spor_outdoor: "https://www.trendurunlermarket.com/spor-outdoor-C10"
  hobi_kitap: "https://www.trendurunlermarket.com/hobi-kitap-C11"
  otomotiv: "https://www.trendurunlermarket.com/otomotiv-C13"

max_products_per_category: 30
